AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  HelloWorldTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint: malte.walkowiak@gmx.de
          Protocol: email
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x
      Events:
        HelloWorldApi:
          Type: Api
          Properties:
            Path: /
            Method: GET
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt HelloWorldTopic.TopicName
      Environment:
        Variables:
          SNS_TOPIC_ARN: !Ref HelloWorldTopic
