// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:e1d6329a-6ca9-4aeb-9777-5159323d5992",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_aYOJFsYR1",
    "aws_user_pools_web_client_id": "1hs3vshmc3nodnbv76tv0jcjku",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://pxl4zxtebbem3kib2yj3tl4ghq.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_content_delivery_bucket": "hoursnotes-20200114170828-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "eu-central-1",
    "aws_content_delivery_url": "https://d3l321yj7z92uf.cloudfront.net"
};


export default awsmobile;
