Description: "SAM Demo: Lambda"
Transform: "AWS::Serverless-2016-10-31"

Resources:
  OpenHelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: index.lambdaHandler
      Runtime: nodejs10.x
